fragment AssetFields on Asset {
  sys {
    id
  }
  title
  description
  url
  width
  height
}

fragment ProjectFields on Project {
  sys {
    id
  }
  title
  slug
  subtitle
  shortDescription
  mainImage {
    ...AssetFields
  }
  role
  duration
  year
  tools
  isPasswordProtected
}

fragment AboutMeFields on PortfolioAboutMe {
  json
  links {
    assets {
      block {
        sys {
          id
        }
        url
        title
        width
        height
        description
      }
    }
  }
}

fragment PortfolioFields on Portfolio {
  sys {
    id
  }
  _id
  headline
  githubUrl
  aboutMe {
    ...AboutMeFields
  }
  projectsCollection(limit: 100) {
    items {
      ...ProjectFields
    }
  }
}
